import authRoutes from "../modules/auth/auth.routes";
import adminRoutes from "../modules/admin/admin.routes";
import supportRoutes from "../modules/support/support.routes";
import healthRoutes from "../modules/health/health.routes";
import workoutRoutes from "../modules/workout/workout.routes";
import exerciseRoutes from "../modules/exercise/exercise.routes";
import competitionRoutes from "../modules/competition/competition.routes";
import cronRoutes from "../modules/cron/cron.routes";
import progressRoutes from "../modules/progress/progress.routes";
import uploadRoutes from "../modules/upload/upload.routes";
import securityRoutes from "../modules/security/security.routes";
import dashboardRoutes from "../modules/dashboard/dashboard.routes";
import recommendationRoutes from "../modules/recommendation/recommendation.routes";
import aiRoutes from "../modules/ai/ai.routes";
import { socialRouter } from "../modules/social/social.routes";
import { notificationRouter } from "../modules/notification/notification.routes";
import pushRoutes from "../modules/push/push.routes";
import subscriptionRoutes from "../modules/subscription/subscription.routes";
import { Router } from "express";

const router = Router();

router.use(healthRoutes);
router.use(authRoutes);
router.use(adminRoutes);
router.use(supportRoutes);
router.use(dashboardRoutes);
router.use(exerciseRoutes);
router.use(progressRoutes);
router.use(competitionRoutes);
router.use(cronRoutes);
router.use(uploadRoutes);
router.use(recommendationRoutes);
router.use(workoutRoutes);
router.use(aiRoutes);
router.use("/social", socialRouter);
router.use("/notifications", notificationRouter);
router.use(pushRoutes);
router.use(subscriptionRoutes);
router.use(securityRoutes);

export default router;
